

    if (ranking.style.display == 'none') {
        ranking.style.display = 'block';
        noticias.style.display = 'none';
        inscricao.style.display = 'none';
        regras.style.display = 'none';
        premiacoes.style.display = 'none';
        duvidas.style.display = 'none';
        contato.style.display = 'none';
        carregador.style.display = 'none';
        chat.style.display = 'none';
    } else if(noticias.style.display=='none'){
        noticias.style.display='block';
        ranking.style.display = 'none';
        noticias.style.display = 'none';
        inscricao.style.display = 'none';
        regras.style.display = 'none';
        premiacoes.style.display = 'none';
        duvidas.style.display = 'none';
        contato.style.display = 'none';
        carregador.style.display = 'none';
        chat.style.display = 'none';
    }else if(inscricao.style.display='none'){
        inscricao.style.display='block';
        ranking.style.display = 'none';
        noticias.style.display = 'none';
        inscricao.style.display = 'none';
        regras.style.display = 'none';
        premiacoes.style.display = 'none';
        duvidas.style.display = 'none';
        contato.style.display = 'none';
        carregador.style.display = 'none';
        chat.style.display = 'none';
    }else if(regras.style.display='none'){
        regras.style.display='block';
        inscricao.style.display='none';
        ranking.style.display = 'none';
        noticias.style.display = 'none';
        inscricao.style.display = 'none';
        regras.style.display = 'none';
        premiacoes.style.display = 'none';
        duvidas.style.display = 'none';
        contato.style.display = 'none';
        carregador.style.display = 'none';
        chat.style.display = 'none';
    }else if(premiacoes.style.display='none'){
        premiacoes.style.display='block';
        regras.style.display='none';
        inscricao.style.display='none';
        ranking.style.display = 'none';
        noticias.style.display = 'none';
        inscricao.style.display = 'none';
        regras.style.display = 'none';
        premiacoes.style.display = 'none';
        duvidas.style.display = 'none';
        contato.style.display = 'none';
        carregador.style.display = 'none';
        chat.style.display = 'none';

    }else if(duvidas.style.display=='none'){
        duvidas.style.display='block';
        premiacoes.style.display='none';
        regras.style.display='none';
        inscricao.style.display='none';
        ranking.style.display = 'none';
        noticias.style.display = 'none';
        inscricao.style.display = 'none';
        regras.style.display = 'none';
        premiacoes.style.display = 'none';
        duvidas.style.display = 'none';
        contato.style.display = 'none';
        carregador.style.display = 'none';
        chat.style.display = 'none';
    }else if(contato.style.display=='none'){
        contato.style.display='block';
        duvidas.style.display='none';
        premiacoes.style.display='none';
        regras.style.display='none';
        inscricao.style.display='none';
        ranking.style.display = 'none';
        noticias.style.display = 'none';
        inscricao.style.display = 'none';
        regras.style.display = 'none';
        premiacoes.style.display = 'none';
        duvidas.style.display = 'none';
        contato.style.display = 'none';
        carregador.style.display = 'none';
        chat.style.display = 'none';
    }else if(carregador.style.display=='none'){
        carregador.style.display='block';
        contato.style.display='none';
        duvidas.style.display='none';
        premiacoes.style.display='none';
        regras.style.display='none';
        inscricao.style.display='none';
        ranking.style.display = 'none';
        noticias.style.display = 'none';
        inscricao.style.display = 'none';
        regras.style.display = 'none';
        premiacoes.style.display = 'none';
        duvidas.style.display = 'none';
        contato.style.display = 'none';
        carregador.style.display = 'none';
        chat.style.display = 'none';
    }else if(chat.style.display=='none'){
        chat.style.display='block';
        carregador.style.display='none';
        contato.style.display='none';
        duvidas.style.display='none';
        premiacoes.style.display='none';
        regras.style.display='none';
        inscricao.style.display='none';
        ranking.style.display = 'none';
        noticias.style.display = 'none';
        inscricao.style.display = 'none';
        regras.style.display = 'none';
        premiacoes.style.display = 'none';
        duvidas.style.display = 'none';
        contato.style.display = 'none';
        carregador.style.display = 'none';
        chat.style.display = 'none';
    }